version: 2
updates:
  # Check for Python dependency updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/" # Update actions used in workflows
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
