# Check dependencies for PY3.12
name: Python 3.12

on:
  push: { branches: [main] }
  schedule:
    - cron: '0 6 1 * *' # At 06:00 AM, on day 1 of the month

# Testing dependencies
jobs:
  # Testing for Python 3.12
  python312:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt